# System: PostgreSQL
# Server: db
# Username: postgres
# Password: example
# Database: оставить пустым (или указать postgres).

services:

  db:
    image: postgres:16.4
    restart: always
    shm_size: 128mb
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  web: 
    build: ./
    image: express_image
    container_name: express_container
    command: bash -c "npm install && node ."
    volumes:
      - .:/app
    ports:
      - 3000:3000
    depends_on:
      - db
