# System: PostgreSQL
# Server: db
# Username: postgres
# Password: example
# Database: оставить пустым (или указать postgres).

services:
  db:
    image: postgres:16.4
    container_name: pg_container
    networks:
      - pgnet
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./data:/var/lib/postgresql/data
  adminer:
    image: adminer
    container_name: admin_container
    depends_on:
      - db
    networks:
      - pgnet
    restart: always
    ports:
      - 8080:8080
  web_server: 
    image: node
    container_name: express_container
    depends_on:
      - db
    networks:
      - pgnet
    ports:
      - 3000:3000
    volumes:
      - ./server:/app
    command: bash -c "cd /app && npm install && node ."
  web_client:
    image: node
    container_name: redux_container
    depends_on:
      - web_server
    networks:
      - pgnet
    ports:
      - 5173:5173
    volumes:
      - ./client:/app
    command: bash -c "cd /app && npm install && npm run dev -- --host"

networks:
  pgnet:
    name: pgnet
    driver: bridge